elasticsearch:
    image: elasticsearch:latest
    ports: 
        - "9200:9200"

win-logstash:
    build: .
    links: 
        - elasticsearch
    ports:
        - "5000:5000"
    command: logstash -f /config-dir/logstash.conf

kibana:
    image: kibana:latest
    ports:
        - "5601:5601"
    links: 
        - elasticsearch
